[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
optimizer = true
optimizer_runs = 200
solc="0.8.19"

[fmt]
tab_width = 2
line_length = 100
bracket_spacing = true
